# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olaf', '0004_remove_userdata_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpirableTokenField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256)),
                ('expiration_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={'ordering': ['-wins', 'loses', '-ties']},
        ),
        migrations.AddField(
            model_name='expirabletokenfield',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='olaf.UserData'),
        ),
    ]
